# -*- coding: utf-8 -*-
"""loan_default project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yrk9gMrEJDMCVrKqs5qEAKmY4e3b7dXH

##  Project: Loan Default Prediction
## Author: Aastha Shinde

**Project Overview:**
The objective of this project is to build a machine learning model that predicts the likelihood of a borrower defaulting on a loan. Using financial data such as income, credit scores, and loan amounts, we aim to provide banks with a robust risk assessment tool to minimize financial losses and optimize the lending process.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve

# Settings
# %matplotlib inline
sns.set_theme(style="whitegrid")
warnings.filterwarnings('ignore')

# Load the dataset
df = pd.read_csv('/content/Loan_default.csv')

df.head()

df.shape

"""# 1. Target Variable Distribution"""

plt.figure(figsize=(6, 4))
sns.countplot(x='Default', data=df, palette='Set1')
plt.title('Loan Default Status (0: Safe, 1: Default)', fontweight='bold')
plt.show()

"""# 2. Correlation Heatmap"""

plt.figure(figsize=(12, 10))
# Encoding temporarily for heatmap
df_temp = df.copy()
for col in df_temp.select_dtypes(include=['object']).columns:
    df_temp[col] = LabelEncoder().fit_transform(df_temp[col])

sns.heatmap(df_temp.corr(), annot=True, cmap='RdYlGn', fmt='.2f')
plt.title('Feature Correlation Heatmap', fontweight='bold')
plt.show()

"""# 3. Income vs Default"""

plt.figure(figsize=(8, 5))
sns.boxplot(x='Default', y='Income', data=df)
plt.title('Income Level vs Default Status', fontweight='bold')
plt.show()

"""##Loan Amount vs. Income"""

# Drop non-predictive identifier
df_clean = df.drop(['LoanID'], axis=1)

# Encode Categorical features into numbers
categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
                    'HasDependents', 'LoanPurpose', 'HasCoSigner']

le = LabelEncoder()
for col in categorical_cols:
    df_clean[col] = le.fit_transform(df_clean[col])

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Income', y='LoanAmount', hue='Default', data=df_clean, alpha=0.5, palette='coolwarm')
plt.title('Loan Amount vs. Income (Colored by Default)')
plt.show()

# Drop non-predictive identifier
df_clean = df.drop(['LoanID'], axis=1)

# Encode Categorical Variables
categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
                    'HasDependents', 'LoanPurpose', 'HasCoSigner']

le = LabelEncoder()
for col in categorical_cols:
    df_clean[col] = le.fit_transform(df_clean[col])

print("✅ Categorical features encoded.")
df_clean.head()

# Defining Features (X) and Target (y)
# Drop rows where the target variable 'Default' is NaN before defining X and y
df_clean_no_nan = df_clean.dropna(subset=['Default'])
X = df_clean_no_nan.drop('Default', axis=1)
y = df_clean_no_nan['Default']

# Splitting: 80% Training, 20% Testing
# Note: stratify=y is used to maintain the ratio of defaults in both sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Standardizing numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("✅ Data split and scaled.")

# Save the scaler
joblib.dump(scaler, 'loan_scaler.pkl')
print("✅ Scaler saved as 'loan_scaler.pkl'")

# Save the scaler
joblib.dump(scaler, 'loan_scaler.pkl')
print("✅ Scaler saved as 'loan_scaler.pkl'")

# Make sure THIS cell is executed first
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import ConfusionMatrixDisplay

# List to store results for final comparison
model_performance = []

def evaluate_model(model, name, x_train, x_test, y_train, y_test, is_scaled=False):
    # Train
    model.fit(x_train, y_train)
    # Predict
    preds = model.predict(x_test)

    # Calculate Metrics
    acc = accuracy_score(y_test, preds)
    report = classification_report(y_test, preds)

    print(f"\n{'='*20} {name} {'='*20}")
    print(f"Accuracy Score: {acc:.4f}")
    print("\nClassification Report:")
    print(report)

    # Plot Confusion Matrix
    fig, ax = plt.subplots(figsize=(5, 4))
    ConfusionMatrixDisplay.from_estimator(model, x_test, y_test, cmap='Blues', ax=ax)
    plt.title(f'Confusion Matrix: {name}')
    plt.grid(False)
    plt.show()

    return acc, model # Return the trained model as well

lr_acc = evaluate_model(LogisticRegression(max_iter=1000), "Logistic Regression",
                        X_train_scaled, X_test_scaled, y_train, y_test)

dt_acc = evaluate_model(DecisionTreeClassifier(max_depth=6, random_state=42), "Decision Tree",
                        X_train, X_test, y_train, y_test)

rf_acc, rf_model = evaluate_model(RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42), "Random Forest",
                        X_train, X_test, y_train, y_test)

# Save the Random Forest model
joblib.dump(rf_model, 'loan_default_model.pkl')
print("✅ Random Forest model saved as 'loan_default_model.pkl'")

# Save the Random Forest model
joblib.dump(rf_model, 'loan_default_model.pkl')
print("✅ Random Forest model saved as 'loan_default_model.pkl'")

knn_acc = evaluate_model(KNeighborsClassifier(n_neighbors=5), "K-Nearest Neighbors",
                         X_train_scaled, X_test_scaled, y_train, y_test)

svm_acc = evaluate_model(LinearSVC(random_state=42), "Support Vector Machine",
                         X_train_scaled, X_test_scaled, y_train, y_test)

gb_acc = evaluate_model(GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42), "Gradient Boosting",
                        X_train, X_test, y_train, y_test)

# Create a summary table
results_df = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest', 'KNN', 'SVM', 'Gradient Boosting'],
    'Accuracy': [lr_acc, dt_acc, rf_acc, knn_acc, svm_acc, gb_acc]
}).sort_values(by='Accuracy', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Accuracy', y='Model', data=results_df, palette='magma')
plt.title('Comparison of 6 ML Models by Accuracy', fontweight='bold')
plt.xlim(0.8, 1.0) # Adjust based on your results
plt.show()

display(results_df)

!pip install streamlit
import streamlit as st
import pandas as pd
import joblib
import numpy as np

# 1. Load the saved model and scaler
# Ensure these files are saved in the environment (e.g., in the current directory)
try:
    model = joblib.load('loan_default_model.pkl')
    scaler = joblib.load('loan_scaler.pkl')
    st.success("✅ Model and Scaler loaded successfully!")
except FileNotFoundError:
    st.error("Error: Model or scaler files not found. Please ensure 'loan_default_model.pkl' and 'loan_scaler.pkl' are saved.")
    st.stop() # Stop the app if files are not found

# 2. App Title and Description
st.set_page_config(page_title="Loan Default Predictor", layout="wide")
st.title("🏦 Banking Risk Analytics: Loan Default Prediction")
st.markdown("Developed by **Aastha Shinde** | BIA Capstone Project")
st.write("Enter the applicant's details below to assess the risk of default.")

# 3. Create Input Fields (Matching your dataset features)
col1, col2, col3 = st.columns(3)

with col1:
    age = st.number_input("Age", min_value=18, max_value=100, value=30)
    income = st.number_input("Annual Income ($)", min_value=0, value=50000)
    loan_amount = st.number_input("Loan Amount ($)", min_value=0, value=15000)
    credit_score = st.number_input("Credit Score", min_value=300, max_value=850, value=650)

with col2:
    months_employed = st.number_input("Months Employed", min_value=0, value=24)
    num_credit_lines = st.number_input("Number of Credit Lines", min_value=0, value=2)
    interest_rate = st.number_input("Interest Rate (%)", min_value=0.0, max_value=35.0, value=10.0)
    loan_term = st.selectbox("Loan Term (Months)", [12, 24, 36, 48, 60])

with col3:
    dti_ratio = st.slider("DTI Ratio (Debt-to-Income)", 0.0, 1.0, 0.4)
    education = st.selectbox("Education", ["High School", "Bachelor's", "Master's", "PhD"])
    employment_type = st.selectbox("Employment Type", ["Full-time", "Part-time", "Self-employed", "Unemployed"])
    marital_status = st.selectbox("Marital Status", ["Single", "Married", "Divorced"])

# Binary features
has_mortgage = st.selectbox("Has Mortgage?", ["No", "Yes"])
has_dependents = st.selectbox("Has Dependents?", ["No", "Yes"])
loan_purpose = st.selectbox("Loan Purpose", ["Auto", "Business", "Education", "Home", "Other"])
has_cosigner = st.selectbox("Has Co-Signer?", ["No", "Yes"])

# Categorical mapping (Same as LabelEncoder in training)
# Note: Ensure these match your LabelEncoder classes! (Mapping based on df_clean.head() and common encoding practices)
edu_map = {"Bachelor's": 0, "High School": 1, "Master's": 2, "PhD": 3}
emp_map = {"Full-time": 0, "Part-time": 1, "Self-employed": 2, "Unemployed": 3}
mar_map = {"Divorced": 0, "Married": 1, "Single": 2}
pur_map = {"Auto": 0, "Business": 1, "Education": 2, "Home": 3, "Other": 4}

# Binary features mapping
has_mortgage_map = {"No": 0, "Yes": 1}
has_dependents_map = {"No": 0, "Yes": 1}
has_cosigner_map = {"No": 0, "Yes": 1}

# 4. Prediction Logic
if st.button("Predict Default Risk"):
    # Create the feature array in the exact order as X_train
    features = np.array([[age, income, loan_amount, credit_score, months_employed,
                          num_credit_lines, interest_rate, loan_term, dti_ratio,
                          edu_map[education], emp_map[employment_type], mar_map[marital_status],
                          has_mortgage_map[has_mortgage], has_dependents_map[has_dependents],
                          pur_map[loan_purpose], has_cosigner_map[has_cosigner]]])

    # Scale numerical features
    scaled_features = scaler.transform(features)

    prediction = model.predict(scaled_features)
    probability = model.predict_proba(scaled_features)[0][1]

    # 5. Display Result
    st.divider()
    if prediction[0] == 1:
        st.error(f"⚠️ HIGH RISK: The model predicts a high probability of DEFAULT ({probability:.2%})")
    else:
        st.success(f"✅ LOW RISK: The applicant is likely to be SAFE ({1-probability:.2%} confidence)")

import joblib

# 1. Save the trained model
# Ensure 'rf_model' was defined in a previous cell
joblib.dump(rf_model, 'loan_default_model.pkl')

# 2. Save the scaler
# (You created this in the Preprocessing/Scaling step)
joblib.dump(scaler, 'loan_scaler.pkl')

print("✅ Success: Model and Scaler have been saved successfully!")

